CREATE TABLE booking (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT NOT NULL,
    code VARCHAR(100),
    journey_code VARCHAR(100),
    contact_email VARCHAR(256) NOT NULL,
    contact_first_name VARCHAR(256) NOT NULL,
    contact_last_name VARCHAR(256) NOT NULL,
    contact_title VARCHAR(50) NOT NULL,
    contact_nationality VARCHAR(50) NOT NULL,
    contact_phone_code VARCHAR(4) NOT NULL,
    contact_phone_number VARCHAR(20) NOT NULL,
    contact_dob DATE NULL,
    additional_info JSON,
    client_additional_info JSON,
    status SMALLINT NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE booking_pax (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    email VARCHAR(256),
    first_name VARCHAR(256) NOT NULL,
    last_name VARCHAR(256) NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(50) NOT NULL,
    nationality VARCHAR(50),
    phone_code VARCHAR(4),
    phone_number VARCHAR(20),
    dob DATE,
    add_on JSON,
    issuing_country VARCHAR(50),
    document_type VARCHAR(50),
    document_no VARCHAR(128),
    expiration_date DATE,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_booking_id (booking_id)
);
